markdown: kramdown
baseurl: http://www.jeansoto.com
# baseurl: ''
exclude: ["node_modules", "vendor", "gulpfile.js", "package.json", "README.md"]
permalink: pretty
# highlighter: rouge
highlighter: pygments.rb
